name: static check
on:
  push:
    paths:
      - "**.go"
  pull_request:
    paths:
      - "**.go"
      - .github/workflows/golangci.yml

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Setup Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: set up go
        run: go mod download

      - name: Confirm GO
        run: go env && pwd

      - name: Run gofmt
        run: gofmt -l -s -w .

      - name: Install goimports
        run:  go install golang.org/x/tools/cmd/goimports@latest
        env:
          GO111MODULE: on

      - name: Run goimports
        run: goimports -w .

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--config=./.golangci.yml ./..."
          fail_on_error: true
          reporter: "github-pr-review"

      - name: Slack Notification on Failure
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        if: ${{ failure() }}
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "リポジトリ: ${{ github.repository }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "デプロイ失敗しました😢\n result: ${{ job.status }}\n ${{ github.workflow }} Action: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
